import Head from "next/head";
import Link from "next/link";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import { useState } from "react";
import { getSortedPostsData, Meta } from "../lib/posts";

export default function Home({ allPostsData }: { allPostsData: Meta[] }) {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title className="">Shachaks Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-gray-800 px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-end">
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(false)}
                    className="cursor-pointer text-2xl dark:text-gray-300"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(true)}
                    className="cursor-pointer text-2xl dark:text-gray-300"
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-600 to-teal-600 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="relative mx-auto bg-gradient-to-b from-teal-600 rounded-full w-44 h-44 md:w-56 md:h-56 mt-20 overflow-clip">
            <Image src={deved} alt="" fill className=" object-cover" />
          </div>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Shachak Zicher
            </h2>
            <h3 className="text-2xl py-2 dark:text-gray-300">Developer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-400">
              bla bla bla bla bla
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-500">
            <AiFillTwitterCircle />
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
        </section>
        <section className="m-10">
          <h1 className="text-2xl mb-3">Blog</h1>
          <ul>
            {allPostsData.map(({ slug, date, title }) => (
              <li key={slug} className="mb-3 divide-y-reverse">
                <Link
                  href={`/posts/${slug}`}
                  className="mb-1 text-xl underline"
                >
                  {title}
                </Link>
                <div className="flex justify-between">
                  <span>{slug}</span>
                  <span>{`${date}`}</span>
                </div>
              </li>
            ))}
          </ul>
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData
    }
  };
}
